#!/bin/bash
# reprap-host -- runs RepRap Java host with an appropriate classpath

REPRAP_RAM_SIZE=1024M                # Amount of RAM to allow Java VM to use
REPRAP_DIR=`dirname $0`       # reprap.jar, jni libs and stl file

cd $REPRAP_DIR

MACHINE=`uname -m`

# put the directory with the native RXTX and j3d libs in the library path
LD_LIBRARY_PATH=`pwd`/lib-${MACHINE}:${LD_LIBRARY_PATH}
export LD_LIBRARY_PATH

# build up classpath
# when we move to OpenJDK/Java-6 these next few can be replaced with wildcard
# *.jar and we will not need swing-layout any more.
CLASSPATH=./reprap.jar
CLASSPATH=$CLASSPATH:./j3dcore.jar
CLASSPATH=$CLASSPATH:./j3d-org-java3d-all.jar
CLASSPATH=$CLASSPATH:./j3dutils.jar
CLASSPATH=$CLASSPATH:./vecmath.jar
CLASSPATH=$CLASSPATH:./RXTXcomm.jar
CLASSPATH=$CLASSPATH:./swing-layout-1.0.3.jar
CLASSPATH=$CLASSPATH:.

# invoke the code
java -cp $CLASSPATH -Xmx$REPRAP_RAM_SIZE org.reprap.Main
