.TH reprap-host 1 "(c) Adrian Bowyer & The University of Bath"
.SH NAME
reprap-host - Host software to perform 3D Printing on a RepRap
.SH SYNOPSIS
.B reprap-host
.SH WARNING
The information in this man page is extremely limited.  For further
information, see the forums at http://forums.reprap.org .
.SH DESCRIPTION
.B reprap-host
is a controller program for the RepRap 3D printing hardware.  It can load STL files
and instruct the RepRap hardware to "print" (extrude) the objects corresponding to
those STL files.
.B reprap-host
is part of the RepRap project.  See http://www.reprap.org for more.
.SH OPTIONS
.B reprap-host
currently takes no options at all.  It is just a simple shell script
to invoke the Java code with an appropriate classpath.
.SH SEE ALSO
http://www.reprap.org http://forums.reprap.org
.SH AUTHOR
Adrian Bowyer <A.Bowyer@bath.ac.uk>
.SH COPYRIGHT
(c) 2006, 2007 Adrian Bowyer & The University of Bath

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as
published by the Free Software Foundation, version 2.1 only.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the Lesser GNU General Public
License along with this program; if not, write to the Free Software
Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
