; reprap-stls.nsi

; reprap STL Files for Reprap Parts -- included by reprap-host.nsi

; Authors: Bruce Wattendorf and Jonathan Marsden

; Date: 2007-12-31

  SetOutPath "$INSTDIR\Reprap parts"
  SetOverwrite try
  File "reprap-cartesian-bot-1.0.4\handmade-parts.pdf"
  File "reprap-cartesian-bot-1.0.4\LICENSE.txt"
  SetOutPath "$INSTDIR\Reprap parts\non-printed-parts"
  File "reprap-cartesian-bot-1.0.4\non-printed-parts\Bed.stl"
  File "reprap-cartesian-bot-1.0.4\non-printed-parts\Caliper-head.stl"
  File "reprap-cartesian-bot-1.0.4\non-printed-parts\Caliper-rail-short.stl"
  File "reprap-cartesian-bot-1.0.4\non-printed-parts\Caliper-rail.stl"
  File "reprap-cartesian-bot-1.0.4\non-printed-parts\Comms-power-board.stl"
  File "reprap-cartesian-bot-1.0.4\non-printed-parts\Diagonal-studding-base.stl"
  File "reprap-cartesian-bot-1.0.4\non-printed-parts\Diagonal-studding-side.stl"
  SetOutPath "$INSTDIR\Reprap parts\non-printed-parts\Fasteners"
  File "reprap-cartesian-bot-1.0.4\non-printed-parts\Fasteners\M3-cap-x-10.stl"
  File "reprap-cartesian-bot-1.0.4\non-printed-parts\Fasteners\M3-cap-x-25.stl"
  File "reprap-cartesian-bot-1.0.4\non-printed-parts\Fasteners\M3-nut.stl"
  File "reprap-cartesian-bot-1.0.4\non-printed-parts\Fasteners\M3-washer.stl"
  File "reprap-cartesian-bot-1.0.4\non-printed-parts\Fasteners\M5-nut.stl"
  File "reprap-cartesian-bot-1.0.4\non-printed-parts\Fasteners\M5-socket-bolt-x-15.stl"
  File "reprap-cartesian-bot-1.0.4\non-printed-parts\Fasteners\M5-socket-bolt-x-20.stl"
  File "reprap-cartesian-bot-1.0.4\non-printed-parts\Fasteners\M5-socket-bolt-x-30.stl"
  File "reprap-cartesian-bot-1.0.4\non-printed-parts\Fasteners\M5-socket-bolt-x-40.stl"
  File "reprap-cartesian-bot-1.0.4\non-printed-parts\Fasteners\M5-socket-bolt-x-50.stl"
  File "reprap-cartesian-bot-1.0.4\non-printed-parts\Fasteners\M5-washer.stl"
  File "reprap-cartesian-bot-1.0.4\non-printed-parts\Fasteners\M5-x-8-grub.stl"
  File "reprap-cartesian-bot-1.0.4\non-printed-parts\Fasteners\M8-nut.stl"
  File "reprap-cartesian-bot-1.0.4\non-printed-parts\Fasteners\M8-washer.stl"
  SetOutPath "$INSTDIR\Reprap parts\non-printed-parts"
  File "reprap-cartesian-bot-1.0.4\non-printed-parts\Motor-stepper-ST5709S1208-B-plain-shaft-short.stl"
  File "reprap-cartesian-bot-1.0.4\non-printed-parts\Motor-stepper-ST5709S1208-B-plain-shaft.stl"
  File "reprap-cartesian-bot-1.0.4\non-printed-parts\Opto-PCB.stl"
  File "reprap-cartesian-bot-1.0.4\non-printed-parts\Optoswitch-RS304560.stl"
  File "reprap-cartesian-bot-1.0.4\non-printed-parts\Universal-PCB.stl"
  File "reprap-cartesian-bot-1.0.4\non-printed-parts\X-bar-idler.stl"
  File "reprap-cartesian-bot-1.0.4\non-printed-parts\X-bar-slide.stl"
  File "reprap-cartesian-bot-1.0.4\non-printed-parts\X-belt.stl"
  File "reprap-cartesian-bot-1.0.4\non-printed-parts\X-caliper-head-clamp.stl"
  File "reprap-cartesian-bot-1.0.4\non-printed-parts\XY-frame-bar.stl"
  File "reprap-cartesian-bot-1.0.4\non-printed-parts\Y-bar-drive.stl"
  File "reprap-cartesian-bot-1.0.4\non-printed-parts\Y-bar-idler.stl"
  File "reprap-cartesian-bot-1.0.4\non-printed-parts\Y-belt.stl"
  File "reprap-cartesian-bot-1.0.4\non-printed-parts\Y-post.stl"
  File "reprap-cartesian-bot-1.0.4\non-printed-parts\Z-bar-long.stl"
  File "reprap-cartesian-bot-1.0.4\non-printed-parts\Z-bar-short.stl"
  File "reprap-cartesian-bot-1.0.4\non-printed-parts\Z-belt.stl"
  File "reprap-cartesian-bot-1.0.4\non-printed-parts\Z-studding-drive.stl"
  File "reprap-cartesian-bot-1.0.4\non-printed-parts\Z-studding-idler.stl"
  SetOutPath "$INSTDIR\Reprap parts\printed-parts"
  File "reprap-cartesian-bot-1.0.4\printed-parts\Bearing-insert-180-X.stl"
  File "reprap-cartesian-bot-1.0.4\printed-parts\Bearing-insert-180-Z.stl"
  File "reprap-cartesian-bot-1.0.4\printed-parts\Bearing-insert-360-jam.stl"
  File "reprap-cartesian-bot-1.0.4\printed-parts\Bearing-insert-360-run.stl"
  File "reprap-cartesian-bot-1.0.4\printed-parts\Bed-clamp.stl"
  File "reprap-cartesian-bot-1.0.4\printed-parts\Bed-constraint-bracket.stl"
  File "reprap-cartesian-bot-1.0.4\printed-parts\Bed-corner.stl"
  File "reprap-cartesian-bot-1.0.4\printed-parts\Circlip-M8.stl"
  File "reprap-cartesian-bot-1.0.4\printed-parts\Corner-bracket-vertical-bolt-plug.stl"
  File "reprap-cartesian-bot-1.0.4\printed-parts\Corner-bracket.stl"
  File "reprap-cartesian-bot-1.0.4\printed-parts\Diagonal-tie-bracket.stl"
  File "reprap-cartesian-bot-1.0.4\printed-parts\Extruder-quickfit-dock.stl"
  File "reprap-cartesian-bot-1.0.4\printed-parts\Extruder-quickfit-latch.stl"
  File "reprap-cartesian-bot-1.0.4\printed-parts\Fan-base.stl"
  File "reprap-cartesian-bot-1.0.4\printed-parts\Fan-leg.stl"
  SetOutPath "$INSTDIR\Reprap parts\printed-parts\jigs-and-moulds"
  File "reprap-cartesian-bot-1.0.4\printed-parts\jigs-and-moulds\Foot-spacer.stl"
  File "reprap-cartesian-bot-1.0.4\printed-parts\jigs-and-moulds\X-Blade.stl"
  File "reprap-cartesian-bot-1.0.4\printed-parts\jigs-and-moulds\X-pulley-toothed.stl"
  File "reprap-cartesian-bot-1.0.4\printed-parts\jigs-and-moulds\XY-Belt-collar.stl"
  File "reprap-cartesian-bot-1.0.4\printed-parts\jigs-and-moulds\XY-Pot.stl"
  File "reprap-cartesian-bot-1.0.4\printed-parts\jigs-and-moulds\Y-Blade.stl"
  File "reprap-cartesian-bot-1.0.4\printed-parts\jigs-and-moulds\Y-pulley-toothed.stl"
  File "reprap-cartesian-bot-1.0.4\printed-parts\jigs-and-moulds\Z-belt-splicer.stl"
  File "reprap-cartesian-bot-1.0.4\printed-parts\jigs-and-moulds\Z-toothed-pulley-mould-female.stl"
  File "reprap-cartesian-bot-1.0.4\printed-parts\jigs-and-moulds\Z-toothed-pulley-mould-male.stl"
  File "reprap-cartesian-bot-1.0.4\printed-parts\jigs-and-moulds\Z-toothed-pulley.stl"
  SetOutPath "$INSTDIR\Reprap parts\printed-parts"
  File "reprap-cartesian-bot-1.0.4\printed-parts\Optoswitch-bracket.stl"
  File "reprap-cartesian-bot-1.0.4\printed-parts\PCB-clamp.stl"
  File "reprap-cartesian-bot-1.0.4\printed-parts\X-belt-clamp.stl"
  File "reprap-cartesian-bot-1.0.4\printed-parts\X-carriage.stl"
  File "reprap-cartesian-bot-1.0.4\printed-parts\X-constraint-bracket.stl"
  File "reprap-cartesian-bot-1.0.4\printed-parts\X-idler-bracket.stl"
  File "reprap-cartesian-bot-1.0.4\printed-parts\X-motor-bracket.stl"
  File "reprap-cartesian-bot-1.0.4\printed-parts\X-opto-flag.stl"
  File "reprap-cartesian-bot-1.0.4\printed-parts\X-PCB-bracket.stl"
  File "reprap-cartesian-bot-1.0.4\printed-parts\X-square-jig.stl"
  File "reprap-cartesian-bot-1.0.4\printed-parts\XY-pulley-idler.stl"
  File "reprap-cartesian-bot-1.0.4\printed-parts\Y-bearing-housing.stl"
  File "reprap-cartesian-bot-1.0.4\printed-parts\Y-belt-clamp.stl"
  File "reprap-cartesian-bot-1.0.4\printed-parts\Y-motor-bracket.stl"
  File "reprap-cartesian-bot-1.0.4\printed-parts\Y-motor-coupling.stl"
  File "reprap-cartesian-bot-1.0.4\printed-parts\Y-opto-flag.stl"
  File "reprap-cartesian-bot-1.0.4\printed-parts\Z-flag-adjuster-housing.stl"
  File "reprap-cartesian-bot-1.0.4\printed-parts\Z-flag-clamp.stl"
  File "reprap-cartesian-bot-1.0.4\printed-parts\Z-flag-slider.stl"
  File "reprap-cartesian-bot-1.0.4\printed-parts\Z-motor-bracket.stl"
  File "reprap-cartesian-bot-1.0.4\printed-parts\Z-motor-coupling.stl"
  File "reprap-cartesian-bot-1.0.4\printed-parts\Z-opto-flag.stl"
  File "reprap-cartesian-bot-1.0.4\printed-parts\Z-studding-tie.stl"
  File "reprap-cartesian-bot-1.0.4\printed-parts\Z-toothed-pulley-rim.stl"
;
  SetOutPath "$INSTDIR\Reprap parts"
  File "reprap-cartesian-bot-1.0.4\README.txt"
;
; End of reprap-stls.nsi